markdown:         redcarpet
highlighter:      pygments

remote_theme: tomjoht/documentation-theme-jekyll
url: mcfriend99.github.io
baseurl: /mysql/

title: mysql
tagline: 'A MySQL client implemented in pure Blade.'